# Generated by Django 3.2.25 on 2025-03-25 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicacion',
            old_name='hora_creacion',
            new_name='fecha_publicacion',
        ),
    ]
