# Generated by Django 3.2.25 on 2025-06-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('episodios', models.PositiveIntegerField(default=1)),
                ('temporadas', models.PositiveIntegerField(default=1)),
                ('imagen', models.URLField(blank=True, null=True)),
                ('año', models.DateField(blank=True, null=True)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
