# Generated by Django 3.2.25 on 2025-06-22 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='pais',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='rating_resumen',
            field=models.URLField(blank=True, null=True, verbose_name='Ver breve resumen'),
        ),
    ]
