# Generated by Django 3.2.25 on 2025-06-22 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0002_auto_20250622_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='rating_resumen',
            field=models.URLField(default='youtube.com', verbose_name='Ver breve resumen'),
        ),
    ]
